[package]
name = "ws-test"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
warp = "0.3.7"
futures = "0.3"
once_cell = "1.19.0"
regex = "1.10.6"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
lazy_static = "1.5.0"
base64 = "0.22.1"
log = "0.4.22"
env_logger = "0.11.5"
rand = "0.8.5"
secp256k1 = "0.29.1"

[dependencies.uuid]
version = "1.10.0"
features = ["v4", "fast-rng", "macro-diagnostics"]
